In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [93]:
df = pd.read_csv("round_0_failures_w_headers_20260223.csv")
# df.loc[0, "experiment_name"] = "id"

In [94]:
df.iloc[0:2]

,experiment_id,Read,failure,fit_param_0,fit_param_1,fit_param_2,fit_param_3,fit_param_4,HEPES,Potassium gluatmate,...,Product,PEG4K 40%,RNAse inhibitor,NEB,Pmix,Ribosome,Magnesium acetate,Creatine phosphate,PPK,PolyP
0,id,feature,classifier,regressor,regressor,regressor,regressor,regressor,feature,feature,...,feature,feature,feature,feature,feature,feature,feature,feature,feature,feature
1,PMix-AR-898_B2_GFP-Gext,GFP-Gext,0,0.036993541,3.096320358,1.276416824,0.000592114,4.132259555,50,100,...,plamGFP,0,5,0,16.25,1.836,8,20,0,0

In [95]:
df.iloc[0:2].T.value_counts(dropna=False)

0           1
feature     0                          4
            1                          3
            2                          3
classifier  0                          1
feature     6.25                       1
regressor   3.096320358                1
            1.276416824                1
            0.036993541                1
            0.000592114                1
id          PMix-AR-898_B2_GFP-Gext    1
feature     plamGFP                    1
            GFP-Gext                   1
            8                          1
            5                          1
            50                         1
            3.5                        1
            20                         1
            16.25                      1
            100                        1
            1.836                      1
            0.3                        1
            0.02                       1
regressor   4.132259555                1
Name: count, dtype: int64

In [96]:
# df.loc[:, df.iloc[1] == "discrete"].iloc[2:, :].value_counts()

In [97]:
## Convert the "Read" column to a set of columns that are one hot for each read type
real_one_hot = pd.get_dummies(df["Read"].iloc[1:], prefix="Read").astype(int) ## THIS HAD iloc[2:], BUT SHOULD HAVE iloc[1:]
real_one_hot.loc[0] = "feature"
df = pd.concat([df, real_one_hot], axis=1).drop("Read", axis=1)

In [98]:
real_one_hot

    Read_GFP-F-G35 Read_GFP-Gext Read_GFP-M-G100
1                0             1               0
2                0             1               0
3                0             1               0
4                0             1               0
5                0             1               0
..             ...           ...             ...
129              0             1               0
130              0             1               0
131              0             1               0
132              0             1               0
0          feature       feature         feature

[133 rows x 3 columns]

In [99]:
df

,experiment_id,failure,fit_param_0,fit_param_1,fit_param_2,fit_param_3,fit_param_4,HEPES,Potassium gluatmate,ATP,...,NEB,Pmix,Ribosome,Magnesium acetate,Creatine phosphate,PPK,PolyP,Read_GFP-F-G35,Read_GFP-Gext,Read_GFP-M-G100
0,id,classifier,regressor,regressor,regressor,regressor,regressor,feature,feature,feature,...,feature,feature,feature,feature,feature,feature,feature,feature,feature,feature
1,PMix-AR-898_B2_GFP-Gext,0,0.036993541,3.096320358,1.276416824,0.000592114,4.132259555,50,100,2,...,0,16.25,1.836,8,20,0,0,0,1,0
2,PMix-AR-898_B4_GFP-Gext,0,0.036716143,3.42650925,1.213825641,0.000519577,4.167453729,50,100,2,...,0,15,1.836,8,20,0,0,0,1,0
3,PMix-AR-898_B10_GFP-Gext,0,0.046411262,2.734953119,1.33059502,0.00082622,4.087116017,50,100,2,...,0,15,2.1852,8,20,0,0,0,1,0
4,PMix-AR-898_B12_GFP-Gext,0,0.040439159,2.501731732,1.375690671,0.000815482,4.059527782,50,100,2,...,0,15,1.836,8,20,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,PPK_20250616_E4_GFP-Gext,0,0.012997801,2.983896526,1.098095647,0.000178993,3.92188859,50,100,2,...,1,15,1.8,18,0,2,30,0,1,0
129,PPK_20250616_E7_GFP-Gext,0,0.012634496,3.007663858,1.098095375,0.000178353,3.919534871,50,100,2,...,1,15,1.8,18,0,2,30,0,1,0
130,PPK_20250616_G1_GFP-Gext,0,0.117034697,2.235698388,1.598023914,0.000419718,3.986394177,50,100,2,...,1,15,1.8,18,20,2,30,0,1,0
131,PPK_20250616_G4_GFP-Gext,0,0.114907065,2.541159209,1.551377401,0.000663852,3.997202512,50,100,2,...,1,15,1.8,18,20,2,30,0,1,0
132,PPK_20250616_G7_GFP-Gext,0,0.112343501,2.591821904,1.538104238,0.000566232,4.008836039,50,100,2,...,1,15,1.8,18,20,2,30,0,1,0

In [100]:
## Convert categorical "Product" to one hot (which is just plamGFP or not (= deGFP))
product_bool = (df["Product"].iloc[1:] == "plamGFP").astype(int)
product_bool.loc[0] = "feature"
df["Product_plamGFP"] = product_bool
df = df.drop("Product", axis=1)

In [101]:
# Drop columns that have only constant values
df = df.drop(df.columns[df[1:].nunique() == 1], axis=1)

In [103]:
# corr = df.drop(["experiment_id", "experiment_name"], axis=1).iloc[2:, :].corr()
# plt.imshow(np.abs(corr) > .99)
# plt.show()
# corr

In [ ]:
print(df.columns[11:47])

In [ ]:
## DON'T DO THIS
# df["big_correlated_block"] = df["AlaRS"]
# df = df.drop(df.columns[11:47], axis=1)

In [ ]:
print(df.columns[8:11])

In [ ]:
## DON'T DO THIS EITHER
# df["small_correlated_block"] = df["PEG4K 40%"]
# print(df.columns[8:11])
# df = df.drop(df.columns[8:11], axis=1)

In [104]:
df

,experiment_id,failure,fit_param_0,fit_param_1,fit_param_2,fit_param_3,fit_param_4,DNA,PEG4K 40%,RNAse inhibitor,...,Pmix,Ribosome,Magnesium acetate,Creatine phosphate,PPK,PolyP,Read_GFP-F-G35,Read_GFP-Gext,Read_GFP-M-G100,Product_plamGFP
0,id,classifier,regressor,regressor,regressor,regressor,regressor,feature,feature,feature,...,feature,feature,feature,feature,feature,feature,feature,feature,feature,feature
1,PMix-AR-898_B2_GFP-Gext,0,0.036993541,3.096320358,1.276416824,0.000592114,4.132259555,6.25,0,5,...,16.25,1.836,8,20,0,0,0,1,0,1
2,PMix-AR-898_B4_GFP-Gext,0,0.036716143,3.42650925,1.213825641,0.000519577,4.167453729,6.25,0,5,...,15,1.836,8,20,0,0,0,1,0,1
3,PMix-AR-898_B10_GFP-Gext,0,0.046411262,2.734953119,1.33059502,0.00082622,4.087116017,6.25,0,5,...,15,2.1852,8,20,0,0,0,1,0,1
4,PMix-AR-898_B12_GFP-Gext,0,0.040439159,2.501731732,1.375690671,0.000815482,4.059527782,6.25,0,5,...,15,1.836,8,20,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,PPK_20250616_E4_GFP-Gext,0,0.012997801,2.983896526,1.098095647,0.000178993,3.92188859,5.725714286,2,0,...,15,1.8,18,0,2,30,0,1,0,1
129,PPK_20250616_E7_GFP-Gext,0,0.012634496,3.007663858,1.098095375,0.000178353,3.919534871,5.725714286,2,0,...,15,1.8,18,0,2,30,0,1,0,1
130,PPK_20250616_G1_GFP-Gext,0,0.117034697,2.235698388,1.598023914,0.000419718,3.986394177,5.725714286,2,0,...,15,1.8,18,20,2,30,0,1,0,1
131,PPK_20250616_G4_GFP-Gext,0,0.114907065,2.541159209,1.551377401,0.000663852,3.997202512,5.725714286,2,0,...,15,1.8,18,20,2,30,0,1,0,1
132,PPK_20250616_G7_GFP-Gext,0,0.112343501,2.591821904,1.538104238,0.000566232,4.008836039,5.725714286,2,0,...,15,1.8,18,20,2,30,0,1,0,1

In [105]:
df

,experiment_id,failure,fit_param_0,fit_param_1,fit_param_2,fit_param_3,fit_param_4,DNA,PEG4K 40%,RNAse inhibitor,...,Pmix,Ribosome,Magnesium acetate,Creatine phosphate,PPK,PolyP,Read_GFP-F-G35,Read_GFP-Gext,Read_GFP-M-G100,Product_plamGFP
0,id,classifier,regressor,regressor,regressor,regressor,regressor,feature,feature,feature,...,feature,feature,feature,feature,feature,feature,feature,feature,feature,feature
1,PMix-AR-898_B2_GFP-Gext,0,0.036993541,3.096320358,1.276416824,0.000592114,4.132259555,6.25,0,5,...,16.25,1.836,8,20,0,0,0,1,0,1
2,PMix-AR-898_B4_GFP-Gext,0,0.036716143,3.42650925,1.213825641,0.000519577,4.167453729,6.25,0,5,...,15,1.836,8,20,0,0,0,1,0,1
3,PMix-AR-898_B10_GFP-Gext,0,0.046411262,2.734953119,1.33059502,0.00082622,4.087116017,6.25,0,5,...,15,2.1852,8,20,0,0,0,1,0,1
4,PMix-AR-898_B12_GFP-Gext,0,0.040439159,2.501731732,1.375690671,0.000815482,4.059527782,6.25,0,5,...,15,1.836,8,20,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,PPK_20250616_E4_GFP-Gext,0,0.012997801,2.983896526,1.098095647,0.000178993,3.92188859,5.725714286,2,0,...,15,1.8,18,0,2,30,0,1,0,1
129,PPK_20250616_E7_GFP-Gext,0,0.012634496,3.007663858,1.098095375,0.000178353,3.919534871,5.725714286,2,0,...,15,1.8,18,0,2,30,0,1,0,1
130,PPK_20250616_G1_GFP-Gext,0,0.117034697,2.235698388,1.598023914,0.000419718,3.986394177,5.725714286,2,0,...,15,1.8,18,20,2,30,0,1,0,1
131,PPK_20250616_G4_GFP-Gext,0,0.114907065,2.541159209,1.551377401,0.000663852,3.997202512,5.725714286,2,0,...,15,1.8,18,20,2,30,0,1,0,1
132,PPK_20250616_G7_GFP-Gext,0,0.112343501,2.591821904,1.538104238,0.000566232,4.008836039,5.725714286,2,0,...,15,1.8,18,20,2,30,0,1,0,1

In [106]:
numerical_vals_df = df.loc[1:, 'DNA':].apply(pd.to_numeric)

In [107]:
numerical_vals_df

,DNA,PEG4K 40%,RNAse inhibitor,NEB,Pmix,Ribosome,Magnesium acetate,Creatine phosphate,PPK,PolyP,Read_GFP-F-G35,Read_GFP-Gext,Read_GFP-M-G100,Product_plamGFP
1,6.250000,0,5,0,16.25,1.8360,8,20,0,0,0,1,0,1
2,6.250000,0,5,0,15.00,1.8360,8,20,0,0,0,1,0,1
3,6.250000,0,5,0,15.00,2.1852,8,20,0,0,0,1,0,1
4,6.250000,0,5,0,15.00,1.8360,8,20,0,0,0,1,0,1
5,6.250000,0,5,0,16.25,1.8360,8,20,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,5.725714,2,0,1,15.00,1.8000,18,0,2,30,0,1,0,1
129,5.725714,2,0,1,15.00,1.8000,18,0,2,30,0,1,0,1
130,5.725714,2,0,1,15.00,1.8000,18,20,2,30,0,1,0,1
131,5.725714,2,0,1,15.00,1.8000,18,20,2,30,0,1,0,1
132,5.725714,2,0,1,15.00,1.8000,18,20,2,30,0,1,0,1

In [108]:
minmax_df = pd.DataFrame({'min': numerical_vals_df.min(axis=0), 'max': numerical_vals_df.max(axis=0)}).T #

In [90]:
minmax_df['Ribosome']

min    1.80
max    3.24
Name: Ribosome, dtype: float64

In [109]:
minmax_df.to_csv("dataset-20260223-min-max.csv")

In [110]:
# df2 = df.drop(1) # DROP ID COLUMNS?
df.to_csv("round_0_w_headers_jb-reformat-2026-02-23.csv", index=False)