In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./20260417-iteration-2-data_jl-curated - 20260417-iteration-2-data_jl-curated.csv")

In [3]:
data.columns

Index(['ID', 'Well', 'Date', 'Experiment', 'Name', 'Type', 'PMix ID',
       'NEB in Pmix', '[PMix] (mg/mL)', 'Ribosome ID', '[Ribosome] (uM)',
       'SMS ID', 'tRNA ID', '[tRNA] (ug/uL)', 'DNA ID', '[DNA] (ng/uL)',
       'PMix Vol (uL)', 'Rxn Volume (uL)', '[DNA] (nM)',
       '[Magnesium acetate] (mM)', '[Creatine phosphate] (mM)',
       '[Potassium glutamate] (mM)', '[ATP] (mM)', '[GTP] (mM)',
       '[Amino acid mix] (mM)', '[HEPES] (mM)', '[PPK] (uM)', '[PolyP] (mM)',
       '[CTP] (mM)', '[UTP] (mM)', '[TCEP] (mM)', '[Folinic acid] (mM)',
       '[Spermidine] (mM)', '[RNase Inhib] (U/mL)', 'Reader Type',
       'Reader Serial Number', 'Gain', 'Read Type', 'HEPES ID',
       'Potassium glutamate ID', 'Magnesium acetate ID', 'ATP ID', 'GTP ID',
       'CTP ID', 'UTP ID', 'Creatine phosphate ID', 'TCEP ID',
       'Folinic acid ID', 'Spermidine ID', 'Amino acid mix ID', 'PolyP ID',
       'PPK ID', '[PEG] (%)', '[PEG4K 40%] (%)', 'Product', 'RNase Inhib ID',
       'Condition', 'success', 'sigmoid_steady_state', 'sigmoid_rate (1/h)',
       'sigmoid_time_offset (h)', 'drift_rate (1/h)',
       'drift_rate_time_offset (h)'],
      dtype='object')

In [4]:
data.head()

,ID,Well,Date,Experiment,Name,Type,PMix ID,NEB in Pmix,[PMix] (mg/mL),Ribosome ID,...,[PEG4K 40%] (%),Product,RNase Inhib ID,Condition,success,sigmoid_steady_state,sigmoid_rate (1/h),sigmoid_time_offset (h),drift_rate (1/h),drift_rate_time_offset (h)
0,id,note,note,feature,note,note,note,feature,feature,note,...,note,feature,note,feature,output,output,output,note,output,note
1,NaN,NaN,NaN,categorical,NaN,NaN,NaN,binary,real,NaN,...,NaN,categorical,NaN,categorical,binary,real,real,NaN,real,NaN
2,NIST-standards-PURExpress-plamGFP-deGFP-B2a,B2,11/24/2025 0:00,NIST-standards-PURExpress-plamGFP-deGFP,plamGFP,Sample,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,plamGFP,Unknown,R&D,TRUE,1.262481008,2.91252455,1.532982368,0.038109659,1.836463412
3,NIST-standards-PURExpress-plamGFP-deGFP-B2b,B2,11/24/2025 0:00,NIST-standards-PURExpress-plamGFP-deGFP,plamGFP,Sample,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,plamGFP,Unknown,R&D,TRUE,1.741849148,2.327727283,1.434347605,0.035100957,4.046733281
4,NIST-standards-PURExpress-plamGFP-deGFP-B2c,B2,11/24/2025 0:00,NIST-standards-PURExpress-plamGFP-deGFP,plamGFP,Sample,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,plamGFP,Unknown,R&D,TRUE,2.435744078,2.468947351,1.501297992,0.051621073,2.967282172

In [9]:
best = data[data["Experiment"]=="20260319-DiscoveryPlate-R2"].sort_values(by="sigmoid_steady_state", ascending=False).iloc[0]
best

ID                            20260319-DiscoveryPlate-R2-I14
Well                                                     I14
Date                                          3/19/2026 0:00
Experiment                        20260319-DiscoveryPlate-R2
Name                                 DiscoveryPlate-R2-GES10
                                           ...
sigmoid_steady_state                             0.628644275
sigmoid_rate (1/h)                               1.959195165
sigmoid_time_offset (h)                          1.276556135
drift_rate (1/h)                                 0.013223727
drift_rate_time_offset (h)                        5.02816315
Name: 157, Length: 63, dtype: object

In [13]:
#| label: tbl:best-data-recipe

best

ID                            20260319-DiscoveryPlate-R2-I14
Well                                                     I14
Date                                          3/19/2026 0:00
Experiment                        20260319-DiscoveryPlate-R2
Name                                 DiscoveryPlate-R2-GES10
                                           ...
sigmoid_steady_state                             0.628644275
sigmoid_rate (1/h)                               1.959195165
sigmoid_time_offset (h)                          1.276556135
drift_rate (1/h)                                 0.013223727
drift_rate_time_offset (h)                        5.02816315
Name: 157, Length: 63, dtype: object

In [17]:
print(best.to_markdown())

|                            | 157                             |
|:---------------------------|:--------------------------------|
| ID                         | 20260319-DiscoveryPlate-R2-I14  |
| Well                       | I14                             |
| Date                       | 3/19/2026 0:00                  |
| Experiment                 | 20260319-DiscoveryPlate-R2      |
| Name                       | DiscoveryPlate-R2-GES10         |
| Type                       | Sample                          |
| PMix ID                    | AR-975                          |
| NEB in Pmix                | FALSE                           |
| [PMix] (mg/mL)             | 1.8                             |
| Ribosome ID                | AR-905                          |
| [Ribosome] (uM)            | 1.8                             |
| SMS ID                     | 220260319-DiscoveryPlate-R2-SMS |
| tRNA ID                    | AR-902                          |
| [tRNA] (ug/uL)             | 2.8                             |
| DNA ID                     | AR-1028                         |
| [DNA] (ng/uL)              | 0                               |
| PMix Vol (uL)              | 0                               |
| Rxn Volume (uL)            | 10                              |
| [DNA] (nM)                 | 5                               |
| [Magnesium acetate] (mM)   | 15                              |
| [Creatine phosphate] (mM)  | 53                              |
| [Potassium glutamate] (mM) | 100                             |
| [ATP] (mM)                 | 3.5                             |
| [GTP] (mM)                 | 2.7                             |
| [Amino acid mix] (mM)      | 0.3815                          |
| [HEPES] (mM)               | 50                              |
| [PPK] (uM)                 | 0                               |
| [PolyP] (mM)               | 0                               |
| [CTP] (mM)                 | 1                               |
| [UTP] (mM)                 | 1                               |
| [TCEP] (mM)                | 1                               |
| [Folinic acid] (mM)        | 0.02                            |
| [Spermidine] (mM)          | 2                               |
| [RNase Inhib] (U/mL)       | 2000                            |
| Reader Type                | Cytation5                       |
| Reader Serial Number       | 1705168                         |
| Gain                       | ext                             |
| Read Type                  | M                               |
| HEPES ID                   | AR-977                          |
| Potassium glutamate ID     | AR-954                          |
| Magnesium acetate ID       | new-Jon                         |
| ATP ID                     | AR-970                          |
| GTP ID                     | AR-971                          |
| CTP ID                     | AR-972                          |
| UTP ID                     | AR-973                          |
| Creatine phosphate ID      | AR-702                          |
| TCEP ID                    | Unknown                         |
| Folinic acid ID            | AR-959                          |
| Spermidine ID              | AR-967                          |
| Amino acid mix ID          | AR-969                          |
| PolyP ID                   | Unknown                         |
| PPK ID                     | Unknown                         |
| [PEG] (%)                  | 0                               |
| [PEG4K 40%] (%)            | 0                               |
| Product                    | deGFP                           |
| RNase Inhib ID             | Unknown                         |
| Condition                  | Labcraft                        |
| success                    | TRUE                            |
| sigmoid_steady_state       | 0.628644275                     |
| sigmoid_rate (1/h)         | 1.959195165                     |
| sigmoid_time_offset (h)    | 1.276556135                     |
| drift_rate (1/h)           | 0.013223727                     |
| drift_rate_time_offset (h) | 5.02816315                      |

# Best historical experiment

In [19]:
data[data["Experiment"]!="20260319-DiscoveryPlate-R2"].sort_values(by="sigmoid_steady_state", ascending=False)

,ID,Well,Date,Experiment,Name,Type,PMix ID,NEB in Pmix,[PMix] (mg/mL),Ribosome ID,...,[PEG4K 40%] (%),Product,RNase Inhib ID,Condition,success,sigmoid_steady_state,sigmoid_rate (1/h),sigmoid_time_offset (h),drift_rate (1/h),drift_rate_time_offset (h)
1,NaN,NaN,NaN,categorical,NaN,NaN,NaN,binary,real,NaN,...,NaN,categorical,NaN,categorical,binary,real,real,NaN,real,NaN
0,id,note,note,feature,note,note,note,feature,feature,note,...,note,feature,note,feature,output,output,output,note,output,note
178,Genscript-PPK-custom-Smix-H8,H8,3/25/2026 0:00,Genscript-PPK-custom-Smix,CP/CK + PPK/polyP + 18 mM Mg2+,Sample,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,plamGFP,Unknown,R&D,TRUE,3.863057942,2.108855855,1.308635588,0.085991521,4.26679363
172,Genscript-PPK-custom-Smix-D8,D8,3/25/2026 0:00,Genscript-PPK-custom-Smix,CP/CK + polyP + 18 mM Mg,Sample,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,plamGFP,Unknown,R&D,TRUE,3.720515759,2.445137589,1.244438088,0.083169605,3.464067324
170,Genscript-PPK-custom-Smix-D10,D10,3/25/2026 0:00,Genscript-PPK-custom-Smix,CP/CK + polyP + 18 mM Mg,Sample,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,plamGFP,Unknown,R&D,TRUE,3.429616565,2.628195601,1.220415524,0.083627998,2.898549445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,Pmix-MFG-116-B8,B8,12/18/2025 0:00,Pmix-MFG-116,Negative,Negative Control,NEB Sol B,TRUE,1.8,NEB Sol B,...,0,Unknown,Unknown,MFG,FALSE,0.002854253,NaN,NaN,NaN,NaN
98,20260309-DiscoveryPlate-R1-H12,H12,3/9/2026 0:00,20260309-DiscoveryPlate-R1,DiscoveryPlate-R1-H12,Sample,AR-975,FALSE,2.030823266,AR-905,...,0,deGFP,Unknown,Labcraft,FALSE,0.002702078,NaN,NaN,NaN,NaN
97,20260309-DiscoveryPlate-R1-H11,H11,3/9/2026 0:00,20260309-DiscoveryPlate-R1,DiscoveryPlate-R1-H11,Sample,AR-975,FALSE,1.763142289,AR-905,...,0,deGFP,Unknown,Labcraft,FALSE,0.002192955,NaN,NaN,NaN,NaN
114,20260309-DiscoveryPlate-R1-J10,J10,3/9/2026 0:00,20260309-DiscoveryPlate-R1,DiscoveryPlate-R1-J10,Sample,AR-975,FALSE,1.799999952,AR-905,...,0,deGFP,Unknown,Labcraft,FALSE,0.002098808,NaN,NaN,NaN,NaN
90,20260309-DiscoveryPlate-R1-G13,G13,3/9/2026 0:00,20260309-DiscoveryPlate-R1,DiscoveryPlate-R1-G13,Sample,AR-975,FALSE,1.555191326,AR-905,...,0,deGFP,Unknown,Labcraft,FALSE,0.000524063,NaN,NaN,NaN,NaN